-- Schema generated from SQLAlchemy models (db/models.py)

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE worlds (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    author_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    is_public BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    image VARCHAR(255)
);

CREATE TABLE words (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word VARCHAR(255) NOT NULL,
    translation VARCHAR(255) NOT NULL,
    world_id INTEGER NOT NULL REFERENCES worlds(id) ON DELETE CASCADE
);

CREATE TABLE sentences (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sentence TEXT NOT NULL,
    world_id INTEGER NOT NULL REFERENCES worlds(id) ON DELETE CASCADE
);

CREATE TABLE adventure_sessions (
    join_code VARCHAR(4) PRIMARY KEY,
    world_id INTEGER REFERENCES worlds(id),
    host_id INTEGER REFERENCES users(id)
);

CREATE TABLE adventure_steps (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(4) NOT NULL REFERENCES adventure_sessions(join_code),
    step_number INTEGER NOT NULL
);

CREATE TABLE quiz_steps (
    id INTEGER PRIMARY KEY REFERENCES adventure_steps(id),
    question TEXT
);

CREATE TABLE quiz_options (
    id INTEGER PRIMARY KEY,
    quiz_step_id INTEGER REFERENCES quiz_steps(id),
    text VARCHAR(255),
    is_correct BOOLEAN
);

CREATE TABLE word_order_steps (
    id INTEGER PRIMARY KEY REFERENCES adventure_steps(id),
    sentence_id INTEGER REFERENCES sentences(id)
);
