"""Поправил отношения quiz_option

Revision ID: 0457ba896b44
Revises: 8835c458b22d
Create Date: 2025-05-03 05:19:15.448550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0457ba896b44'
down_revision = '8835c458b22d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
