"""изменения в предложениях - убраны токены, переименован text в sentence

Revision ID: 12c8329894e9
Revises: 6aa59644069c
Create Date: 2025-05-01 14:36:04.320189

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '12c8329894e9'
down_revision = '6aa59644069c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentences', sa.Column('sentence', sa.Text(), nullable=False))
    op.drop_column('sentences', 'tokens')
    op.drop_column('sentences', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentences', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('sentences', sa.Column('tokens', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('sentences', 'sentence')
    # ### end Alembic commands ###
