"""image nullable

Revision ID: 42484a78c303
Revises: 12c8329894e9
Create Date: 2025-05-01 16:42:35.755585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42484a78c303'
down_revision = '12c8329894e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('worlds', 'image',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('worlds', 'image',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
