"""удалил пока что все таблицы связанные с приключением

Revision ID: 50390f610884
Revises: 42484a78c303
Create Date: 2025-05-03 04:54:29.872350

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '50390f610884'
down_revision = '42484a78c303'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_progress')
    op.drop_table('adventure_steps')
    op.drop_table('adventure_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_progress',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('nickname', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('avatar_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('socket_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('joined_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['adventure_sessions.id'], name='player_progress_session_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='player_progress_pkey')
    )
    op.create_table('adventure_sessions',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('world_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('host_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('join_code', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('settings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], name='adventure_sessions_host_id_fkey'),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], name='adventure_sessions_world_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='adventure_sessions_pkey'),
    sa.UniqueConstraint('join_code', name='adventure_sessions_join_code_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('adventure_steps',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('step_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('game_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('content', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['adventure_sessions.id'], name='adventure_steps_session_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='adventure_steps_pkey')
    )
    # ### end Alembic commands ###
