"""add image to world

Revision ID: 5b71506f9208
Revises: 1d40c3840a3e
Create Date: 2025-03-13 13:22:30.505249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b71506f9208'
down_revision = '1d40c3840a3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worlds', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worlds', 'image')
    # ### end Alembic commands ###
