"""Изменены таблицы для приключения

Revision ID: 8835c458b22d
Revises: 50390f610884
Create Date: 2025-05-03 04:57:17.536001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8835c458b22d'
down_revision = '50390f610884'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adventure_sessions',
    sa.Column('join_code', sa.String(length=4), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=True),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('join_code')
    )
    op.create_table('adventure_steps',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('session_id', sa.String(length=4), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['adventure_sessions.join_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_code', sa.String(length=4), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('socket_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['session_code'], ['adventure_sessions.join_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['adventure_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('word_order_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sentence_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['adventure_steps.id'], ),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_step_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_step_id'], ['quiz_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_options')
    op.drop_table('word_order_steps')
    op.drop_table('quiz_steps')
    op.drop_table('player_progress')
    op.drop_table('adventure_steps')
    op.drop_table('adventure_sessions')
    # ### end Alembic commands ###
