name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Шаг 1: Логинимся в Yandex Container Registry
      - name: Log in to Yandex Container Registry
        uses: docker/login-action@v2
        with:
          registry: cr.yandex
          username: oauth
          password: ${{ secrets.YANDEX_CLOUD_KEY }}

      # Шаг 3: Строим Docker образ
      - name: Build Docker image
        run: |
          docker build -t cr.yandex/crph8la4elkq8clar20b/iketel-backend:latest .

      # Шаг 4: Публикуем Docker образ в Yandex Container Registry
      - name: Push Docker image to Yandex Container Registry
        run: |
          docker push cr.yandex/crph8la4elkq8clar20b/iketel-backend:latest


      - name: SSH into server and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i server_key.pem root@${{ secrets.SERVER_IP }} "cd /home && \
            docker-compose pull && \
            docker-compose down && \
            docker-compose up -d && \
            docker system prune -f"
